apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "NewSimpleProgram"
  annotations:
    github.com/project-slug: peterkavelaars/newsimpleApp
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/team-a"
